<?php

namespace Proxies\__CG__\Hetic\SiteBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Category extends \Hetic\SiteBundle\Entity\Category implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getStarPicture()
    {
        $this->__load();
        return parent::getStarPicture();
    }

    public function addArticle(\Hetic\SiteBundle\Entity\Article $articles)
    {
        $this->__load();
        return parent::addArticle($articles);
    }

    public function removeArticle(\Hetic\SiteBundle\Entity\Article $articles)
    {
        $this->__load();
        return parent::removeArticle($articles);
    }

    public function getArticles()
    {
        $this->__load();
        return parent::getArticles();
    }

    public function addArticles(\Hetic\SiteBundle\Entity\Article $articless)
    {
        $this->__load();
        return parent::addArticles($articless);
    }

    public function removeArticles(\Hetic\SiteBundle\Entity\Article $articless)
    {
        $this->__load();
        return parent::removeArticles($articless);
    }

    public function getArticless()
    {
        $this->__load();
        return parent::getArticless();
    }

    public function setDateCreated($dateCreated)
    {
        $this->__load();
        return parent::setDateCreated($dateCreated);
    }

    public function getDateCreated()
    {
        $this->__load();
        return parent::getDateCreated();
    }

    public function setVisible($visible)
    {
        $this->__load();
        return parent::setVisible($visible);
    }

    public function getVisible()
    {
        $this->__load();
        return parent::getVisible();
    }

    public function setLft($lft)
    {
        $this->__load();
        return parent::setLft($lft);
    }

    public function getLft()
    {
        $this->__load();
        return parent::getLft();
    }

    public function setLvl($lvl)
    {
        $this->__load();
        return parent::setLvl($lvl);
    }

    public function getLvl()
    {
        $this->__load();
        return parent::getLvl();
    }

    public function setRgt($rgt)
    {
        $this->__load();
        return parent::setRgt($rgt);
    }

    public function getRgt()
    {
        $this->__load();
        return parent::getRgt();
    }

    public function setRoot($root)
    {
        $this->__load();
        return parent::setRoot($root);
    }

    public function getRoot()
    {
        $this->__load();
        return parent::getRoot();
    }

    public function setParent(\Hetic\SiteBundle\Entity\Category $parent = NULL)
    {
        $this->__load();
        return parent::setParent($parent);
    }

    public function getParent()
    {
        $this->__load();
        return parent::getParent();
    }

    public function addChildren(\Hetic\SiteBundle\Entity\Category $children)
    {
        $this->__load();
        return parent::addChildren($children);
    }

    public function removeChildren(\Hetic\SiteBundle\Entity\Category $children)
    {
        $this->__load();
        return parent::removeChildren($children);
    }

    public function getChildren()
    {
        $this->__load();
        return parent::getChildren();
    }

    public function setCover($cover)
    {
        $this->__load();
        return parent::setCover($cover);
    }

    public function getCover()
    {
        $this->__load();
        return parent::getCover();
    }

    public function getOptionLabel()
    {
        $this->__load();
        return parent::getOptionLabel();
    }

    public function setPath($path)
    {
        $this->__load();
        return parent::setPath($path);
    }

    public function getPath()
    {
        $this->__load();
        return parent::getPath();
    }

    public function addProduit(\Hetic\SiteBundle\Entity\Produit $produits)
    {
        $this->__load();
        return parent::addProduit($produits);
    }

    public function removeProduit(\Hetic\SiteBundle\Entity\Produit $produits)
    {
        $this->__load();
        return parent::removeProduit($produits);
    }

    public function getProduits()
    {
        $this->__load();
        return parent::getProduits();
    }

    public function addImage(\Hetic\SiteBundle\Entity\ImageCategory $images)
    {
        $this->__load();
        return parent::addImage($images);
    }

    public function removeImage(\Hetic\SiteBundle\Entity\ImageCategory $images)
    {
        $this->__load();
        return parent::removeImage($images);
    }

    public function getImages()
    {
        $this->__load();
        return parent::getImages();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'path', 'description', 'cover', 'dateCreated', 'visible', 'lft', 'lvl', 'rgt', 'root', 'articles', 'produits', 'articless', 'parent', 'children', 'images');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}