<?php

namespace Hetic\SiteBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MediasController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Hetic\SiteBundle\Controller\MediasController();
        return $instance;
    }
}
